parameters:
    zikula_zauth_module.user_delete_listener.class: Zikula\ZAuthModule\Listener\UserDeleteListener
    zikula_zauth_module.registration_listener.class: Zikula\ZAuthModule\Listener\RegistrationListener
    zikula_zauth_module.user_event_listener.class: Zikula\ZAuthModule\Listener\UserEventListener
    zikula_zauth_module.authentication_mapping_repository.class: Zikula\ZAuthModule\Entity\Repository\AuthenticationMappingRepository
    zikula_zauth_module.user_verification_repository.class: Zikula\ZAuthModule\Entity\Repository\UserVerificationRepository
    zikula_zauth_module.helper.administration_actions_helper.class: Zikula\ZAuthModule\Helper\AdministrationActionsHelper
    zikula_zauth_module.helper.file_io.class: Zikula\ZAuthModule\Helper\FileIOHelper
    zikula_zauth_module.helper.lost_password_verification_helper.class: Zikula\ZAuthModule\Helper\LostPasswordVerificationHelper
    zikula_zauth_module.helper.registration_verification_helper.class: Zikula\ZAuthModule\Helper\RegistrationVerificationHelper
    zikula_zauth_module.helper.mail_helper.class: Zikula\ZAuthModule\Helper\MailHelper
    zikula_zauth_module.container.link_container.class: Zikula\ZAuthModule\Container\LinkContainer

services:
    zikula_zauth_module.listener.user_delete_listener:
        class: %zikula_zauth_module.user_delete_listener.class%
        argument: ["@zikula_zauth_module.authentication_mapping_repository", "@zikula_zauth_module.user_verification_repository"]
        tags:
            - { name: kernel.event_subscriber }

    zikula_zauth_module.listener.registration_listener:
        class: %zikula_zauth_module.registration_listener.class%
        arguments: ["@zikula_users_module.current_user", "@zikula_permissions_module.api.permission", "@zikula_extensions_module.api.variable", "@zikula_zauth_module.authentication_mapping_repository", "@zikula_zauth_module.helper.registration_verification_helper"]
        tags:
            - { name: kernel.event_subscriber }

    zikula_zauth_module.listener.user_event_listener:
        class: %zikula_zauth_module.user_event_listener.class%
        arguments: ["@session", "@router"]
        tags:
            - { name: kernel.event_subscriber }

    zikula_zauth_module.authentication_mapping_repository:
        class: %zikula_zauth_module.authentication_mapping_repository.class%
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["Zikula\ZAuthModule\Entity\AuthenticationMappingEntity"]

    zikula_zauth_module.user_verification_repository:
        class: %zikula_zauth_module.user_verification_repository.class%
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["Zikula\ZAuthModule\Entity\UserVerificationEntity"]

    zikula_zauth_module.helper.administration_actions_helper:
        class: %zikula_zauth_module.helper.administration_actions_helper.class%
        arguments: ["@zikula_permissions_module.api.permission", "@router", "@translator.default", "@zikula_zauth_module.user_verification_repository", "@zikula_users_module.user_repository"]

    zikula_zauth_module.helper.file_io:
        class: %zikula_zauth_module.helper.file_io.class%
        lazy: true
        arguments: ["@zikula_extensions_module.api.variable", "@zikula_permissions_module.api.permission", "@translator.default", "@validator", "@doctrine.orm.default_entity_manager", "@zikula_zauth_module.helper.mail_helper", "@event_dispatcher", "@zikula_users_module.current_user"]

    zikula_zauth_module.helper.lost_password_verification_helper:
        class: %zikula_zauth_module.helper.lost_password_verification_helper.class%
        lazy: true
        arguments: ["@zikula_zauth_module.user_verification_repository", "@zikula_extensions_module.api.variable"]

    zikula_zauth_module.helper.registration_verification_helper:
        class: %zikula_zauth_module.helper.registration_verification_helper.class%
        lazy: true
        arguments: ["@zikula_permissions_module.api.permission", "@zikula_zauth_module.user_verification_repository", "@zikula_zauth_module.helper.mail_helper", "@zikula_users_module.current_user", "@zikula_users_module.user_repository"]

    zikula_zauth_module.helper.mail_helper:
        class: %zikula_zauth_module.helper.mail_helper.class%
        lazy: true
        arguments: ["@translator.default", "@twig", "@zikula_extensions_module.api.variable", "@zikula_mailer_module.api.mailer"]

    zikula_zauth_module.container.link_container:
        class: %zikula_zauth_module.container.link_container.class%
        arguments: ["@translator.default", "@router", "@zikula_permissions_module.api.permission", "@zikula_extensions_module.api.variable", "@zikula_users_module.current_user", "@zikula_zauth_module.authentication_mapping_repository"]
        tags:
            - { name: zikula.link_container }
